### ISSUE TITLE
Absence of Y chromosome match between confirmed father and son

### ISSUE THREAD

**Issue by damblef** [apriha/lineage#69]
Hi,

I have noticed using various 23andme files that the software does not yield any results for the Y-chromosome when comparing father and sons.  The X matches with the mother but the Y does not with the father.  These are for confirmed genetic relationships.  cM thresholds used where 0.75 and 7.

Any idea why this is happening?

**Comment by apriha** [comment]
Thanks for the question. Currently, no matches are reported for the Y chromosome because most of the Y chromosome does not recombine and there is no genetic map for this. See https://www.ncbi.nlm.nih.gov/pubmed/11237016 .

But I agree that there should be some means to show if the Y chromosome is shared. Perhaps a simple threshold of almost all Y chromosome SNPs matching to start...
